[package]
name = "currently_playing_spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.4.3", features = ["ws", "headers"] }
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.0-beta.7", features = ["derive", "env"] }
futures-util = "0.3.18"
http = "0.2.5"
reqwest = { version = "0.11.7", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.73"
tracing = "0.1.29"
tracing-subscriber = "0.3.4"
tokio = { version = "1.15.0", default-features = false, features = ["io-util", "macros", "rt", "rt-multi-thread", "time", "sync"] }
tower-http = { version = "0.2.0", features = ["fs", "cors"] }

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
