[package]
name = "currently-playing-spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.0-beta.7", features = ["derive", "env"] }
env_logger = "0.9.0"
futures-util = "0.3.18"
log = "0.4.14"
reqwest = { version = "0.11.7", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.73"
tokio = { version = "1.15.0", default-features = false, features = ["io-util", "macros", "rt", "rt-multi-thread", "time", "sync"] }
tokio-tungstenite = "0.16.1"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
