[package]
name = "currently-playing-spotify"
version = "0.1.0"
edition = "2018"


[dependencies]
actix-web = "4.0.0-beta.10"
awc = { version = "3.0.0-beta.9", features= ["rustls"] }
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9.0"
log = "0.4.14"
serde = "1.0.130"
serde_json = "1.0.69"