name: CI - Cargo audit

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}