name: CD - Create and deploy rust binary as Github release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true
        default: '0.0.0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set Cargo.toml with new version
      run: |
        sed -i 's/^version.*/version = "${{ github.event.inputs.tag }}"/' ./Cargo.toml
    - name: Build
      run: cargo build --release
    - name: Stripping binary
      run: strip ./target/release/currently_playing_spotify
    - name: Compressing binary (UPX)
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: ./target/release/currently_playing_spotify
        args: --best --lzma
    - name: Update and commit Cargo.toml with new version
      run: |
        git config --global user.name 'github_actions'
        git config --global user.email 'actions@github.com'
        git add Cargo.toml
        git commit -m "chore: updated Cargo.toml to ${{ github.event.inputs.tag }}"
        git push
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.tag }}
        files: ./target/release/currently_playing_spotify
