name: CD - Create and deploy rust binary as Github release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true
        default: 'v0.0.0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
    - name: Stripping binary
      run: strip ./target/release/currently-playing-spotify
    - name: Compressing binary (UPX)
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: ./target/release/currently-playing-spotify
        args: --best --lzma
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: ./target/release/currently-playing-spotify
